# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: alertDetectionEvent.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='alertDetectionEvent.proto',
  package='energy',
  syntax='proto3',
  serialized_options=b'\n\037com.generac.ces.telemetry.alert',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x19\x61lertDetectionEvent.proto\x12\x06\x65nergy\"\x88\x01\n\x12\x44\x65viceStateHistory\x12\x1c\n\x14\x63urrent_device_state\x18\x01 \x01(\t\x12\x19\n\x11next_device_state\x18\x02 \x01(\t\x12\x1d\n\x15\x63urrent_timestamp_utc\x18\x03 \x01(\x04\x12\x1a\n\x12next_timestamp_utc\x18\x04 \x01(\x04\"<\n\x0f\x45rrorStateEvent\x12\x1a\n\x12\x65rror_device_state\x18\x01 \x01(\t\x12\r\n\x05\x63ount\x18\x02 \x01(\r\"\xfe\x02\n\x13\x41lertDetectionEvent\x12\x11\n\tdevice_id\x18\x01 \x01(\t\x12\x11\n\thost_rcpn\x18\x02 \x01(\t\x12\x0f\n\x07site_id\x18\x03 \x01(\t\x12\x11\n\tsystem_id\x18\x04 \x01(\t\x12\x16\n\x0e\x61lert_category\x18\x05 \x01(\t\x12\x13\n\x0b\x64\x65vice_type\x18\x06 \x01(\t\x12\x14\n\x0c\x64\x65vice_state\x18\x07 \x01(\t\x12\x1b\n\x13latest_device_state\x18\x08 \x01(\t\x12 \n\x18transition_timestamp_utc\x18\t \x01(\x04\x12\x1c\n\x14latest_timestamp_utc\x18\n \x01(\x04\x12\x38\n\x17num_of_errors_in_window\x18\x0b \x03(\x0b\x32\x17.energy.ErrorStateEvent\x12\x43\n\x1f\x64\x65vice_state_transition_history\x18\x0c \x03(\x0b\x32\x1a.energy.DeviceStateHistoryB!\n\x1f\x63om.generac.ces.telemetry.alertb\x06proto3'
)




_DEVICESTATEHISTORY = _descriptor.Descriptor(
  name='DeviceStateHistory',
  full_name='energy.DeviceStateHistory',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='current_device_state', full_name='energy.DeviceStateHistory.current_device_state', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='next_device_state', full_name='energy.DeviceStateHistory.next_device_state', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='current_timestamp_utc', full_name='energy.DeviceStateHistory.current_timestamp_utc', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='next_timestamp_utc', full_name='energy.DeviceStateHistory.next_timestamp_utc', index=3,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=174,
)


_ERRORSTATEEVENT = _descriptor.Descriptor(
  name='ErrorStateEvent',
  full_name='energy.ErrorStateEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='error_device_state', full_name='energy.ErrorStateEvent.error_device_state', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='count', full_name='energy.ErrorStateEvent.count', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=176,
  serialized_end=236,
)


_ALERTDETECTIONEVENT = _descriptor.Descriptor(
  name='AlertDetectionEvent',
  full_name='energy.AlertDetectionEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='device_id', full_name='energy.AlertDetectionEvent.device_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='host_rcpn', full_name='energy.AlertDetectionEvent.host_rcpn', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='site_id', full_name='energy.AlertDetectionEvent.site_id', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='system_id', full_name='energy.AlertDetectionEvent.system_id', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='alert_category', full_name='energy.AlertDetectionEvent.alert_category', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='device_type', full_name='energy.AlertDetectionEvent.device_type', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='device_state', full_name='energy.AlertDetectionEvent.device_state', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='latest_device_state', full_name='energy.AlertDetectionEvent.latest_device_state', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='transition_timestamp_utc', full_name='energy.AlertDetectionEvent.transition_timestamp_utc', index=8,
      number=9, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='latest_timestamp_utc', full_name='energy.AlertDetectionEvent.latest_timestamp_utc', index=9,
      number=10, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='num_of_errors_in_window', full_name='energy.AlertDetectionEvent.num_of_errors_in_window', index=10,
      number=11, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='device_state_transition_history', full_name='energy.AlertDetectionEvent.device_state_transition_history', index=11,
      number=12, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=239,
  serialized_end=621,
)

_ALERTDETECTIONEVENT.fields_by_name['num_of_errors_in_window'].message_type = _ERRORSTATEEVENT
_ALERTDETECTIONEVENT.fields_by_name['device_state_transition_history'].message_type = _DEVICESTATEHISTORY
DESCRIPTOR.message_types_by_name['DeviceStateHistory'] = _DEVICESTATEHISTORY
DESCRIPTOR.message_types_by_name['ErrorStateEvent'] = _ERRORSTATEEVENT
DESCRIPTOR.message_types_by_name['AlertDetectionEvent'] = _ALERTDETECTIONEVENT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DeviceStateHistory = _reflection.GeneratedProtocolMessageType('DeviceStateHistory', (_message.Message,), {
  'DESCRIPTOR' : _DEVICESTATEHISTORY,
  '__module__' : 'alertDetectionEvent_pb2'
  # @@protoc_insertion_point(class_scope:energy.DeviceStateHistory)
  })
_sym_db.RegisterMessage(DeviceStateHistory)

ErrorStateEvent = _reflection.GeneratedProtocolMessageType('ErrorStateEvent', (_message.Message,), {
  'DESCRIPTOR' : _ERRORSTATEEVENT,
  '__module__' : 'alertDetectionEvent_pb2'
  # @@protoc_insertion_point(class_scope:energy.ErrorStateEvent)
  })
_sym_db.RegisterMessage(ErrorStateEvent)

AlertDetectionEvent = _reflection.GeneratedProtocolMessageType('AlertDetectionEvent', (_message.Message,), {
  'DESCRIPTOR' : _ALERTDETECTIONEVENT,
  '__module__' : 'alertDetectionEvent_pb2'
  # @@protoc_insertion_point(class_scope:energy.AlertDetectionEvent)
  })
_sym_db.RegisterMessage(AlertDetectionEvent)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
